version: "3.8"
services:
    backend:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        image: leapbit-chat-backend:latest
        command: node app.js
        ports:
            - "8080:8080"
        volumes:
            - ./server/:/app/server

    frontend:
        build:
            context: .
            dockerfile: ./src/Dockerfile
        image: leapbit-chat-frontend:latest
        ports:
            - "3000:3000"
        volumes:
            - ./:/app/src